In [35]:
import pandas as pd
import numpy as np

In [36]:
df=pd.DataFrame({
    'Age':[20,30,25,None,40,None,23,None],
    'Salary':[30000,45000,None,60000,None,50000,None,55000],
    'Gender':['Male','Female',None,'Male',None,'Female','Male',None],
    'Job':['ML Engineer',np.nan,'Software Engineer',np.nan,'Frontend Developer','ML Engineer',np.nan,'Backend Developernan']
})

In [37]:
df

    Age   Salary  Gender                   Job
0  20.0  30000.0    Male           ML Engineer
1  30.0  45000.0  Female                   NaN
2  25.0      NaN    None     Software Engineer
3   NaN  60000.0    Male                   NaN
4  40.0      NaN    None    Frontend Developer
5   NaN  50000.0  Female           ML Engineer
6  23.0      NaN    Male                   NaN
7   NaN  55000.0    None  Backend Developernan

In [38]:
from sklearn.impute import SimpleImputer

In [39]:
imputer=SimpleImputer(strategy='constant',fill_value='unknown')

In [40]:
df['Gender']

0      Male
1    Female
2      None
3      Male
4      None
5    Female
6      Male
7      None
Name: Gender, dtype: object

In [41]:
imputer.fit_transform(df[['Gender','Job']])

array([['Male', 'ML Engineer'],
       ['Female', 'unknown'],
       [None, 'Software Engineer'],
       ['Male', 'unknown'],
       [None, 'Frontend Developer'],
       ['Female', 'ML Engineer'],
       ['Male', 'unknown'],
       [None, 'Backend Developernan']], dtype=object)

In [42]:
imputer=SimpleImputer(strategy='mean')

In [43]:
imputer.fit_transform(df[['Salary','Age']])

array([[3.00e+04, 2.00e+01],
       [4.50e+04, 3.00e+01],
       [4.80e+04, 2.50e+01],
       [6.00e+04, 2.76e+01],
       [4.80e+04, 4.00e+01],
       [5.00e+04, 2.76e+01],
       [4.80e+04, 2.30e+01],
       [5.50e+04, 2.76e+01]])

In [44]:
from sklearn.cluster import KMeans
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [45]:
df1=pd.read_csv('Instagram visits clustering.csv')

In [46]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2600 entries, 0 to 2599
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   User ID                  2600 non-null   int64
 1   Instagram visit score    2600 non-null   int64
 2   Spending_rank(0 to 100)  2600 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 61.1 KB

In [47]:
df1.head()

   User ID  Instagram visit score  Spending_rank(0 to 100)
0        0                     63                24.050708
1        1                     61                25.223290
2        2                    104                18.528245
3        3                     82                86.890232
4        4                     14                31.492397

In [48]:
df1.drop(columns=['User ID'],inplace=True)

In [54]:
standard_col=['Instagram visit score','Spending_rank(0 to 100)']

In [55]:
preprocessing=ColumnTransformer(
    transformers=[
        ('standardsclaer',StandardScaler(),standard_col)
    ],remainder='passthrough'
)

In [56]:
main_pipeline=Pipeline(
    steps=[
        ('preprocessing',preprocessing),
        ('model',KMeans(n_clusters=2,random_state=42))
    ]
)

In [57]:
main_pipeline.fit(df1)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('standardsclaer',
                                                  StandardScaler(),
                                                  ['Instagram visit score',
                                                   'Spending_rank(0 to '
                                                   '100)'])])),
                ('model', KMeans(n_clusters=2, random_state=42))])

In [58]:
new_customer=pd.DataFrame({
    'Instagram visit score': [100],
    'Spending_rank(0 to 100)': [200]
})

In [59]:
main_pipeline.predict(new_customer)

array([1], dtype=int32)