In [1]:
import pandas as pd

In [2]:
# Series,DataFrame

''' 
Syntax to create series
pandas.Series([1,2,3,4,5])
'''

' \nSyntax to create series\npandas.Series([1,2,3,4,5])\n'

In [4]:
pd.Series([1,2,3,4,5,'Hello'])

0        1
1        2
2        3
3        4
4        5
5    Hello
dtype: object

In [12]:
# data=([22,40],[10])
# ValueError: 3 columns passed, passed data had 2 columns
data=([23,40],[10],[20,30,45])
column_names=('c1','c2','c3')
pd.DataFrame(data,columns=column_names)

   c1    c2    c3
0  23  40.0   NaN
1  10   NaN   NaN
2  20  30.0  45.0

In [15]:
data=([22,10000],[30,50000,5],[20,15000])
column_names=['Age','Salary','Experience']
column_names=pd.DataFrame(data,columns=column_names)
column_names

   Age  Salary  Experience
0   22   10000         NaN
1   30   50000         5.0
2   20   15000         NaN