In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('D:\machine_learning\datasets\studentperformance.csv')

In [3]:
df[(df['gender']=='female') &( df['lunch']=='standard')]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
984,female,group C,some high school,standard,none,74,75,82
986,female,group C,associate's degree,standard,none,40,59,51
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
998,female,group D,some college,standard,completed,68,78,77

# Filter Female records those who scored above 70 in maths

In [4]:
df[(df['gender']=='female')&(df['math score']>70)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
36,female,group D,associate's degree,standard,none,74,81,83
...,...,...,...,...,...,...,...,...
979,female,group C,associate's degree,standard,none,91,95,94
983,female,group A,some college,standard,completed,78,87,91
984,female,group C,some high school,standard,none,74,75,82
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

# Male records and lunch = 'standard'

In [8]:
df[(df['gender']=='male') & (df['lunch']=='standard')]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,76,78,75
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
13,male,group A,some college,standard,completed,78,72,70
16,male,group C,high school,standard,none,88,89,86
...,...,...,...,...,...,...,...,...
981,male,group D,some high school,standard,none,81,78,78
982,male,group B,some high school,standard,completed,79,85,86
985,male,group A,high school,standard,none,57,51,54
987,male,group E,some high school,standard,completed,81,75,76
994,male,group A,high school,standard,none,63,63,62

In [9]:
df.count()

gender                         1000
race/ethnicity                 1000
parental level of education    1000
lunch                          1000
test preparation course        1000
math score                     1000
reading score                  1000
writing score                  1000
dtype: int64

In [10]:
'''  Unique( ) method
     Syntax:-
            df['col_name].unique()
            
            returns total unique values present in a column, should be used for categorical columns'''
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [11]:
''' nunique method 
    df['column_name].nunique
         returns total number of unique values present in the column'''
df['math score'].nunique()

81

In [12]:
df['gender'].nunique()

2

In [13]:
df['math score'].unique()

array([ 72,  69,  90,  47,  76,  71,  88,  40,  64,  38,  58,  65,  78,
        50,  18,  46,  54,  66,  44,  74,  73,  67,  70,  62,  63,  56,
        97,  81,  75,  57,  55,  53,  59,  82,  77,  33,  52,   0,  79,
        39,  45,  60,  61,  41,  49,  30,  80,  42,  27,  43,  68,  85,
        98,  87,  51,  99,  84,  91,  83,  89,  22, 100,  96,  94,  48,
        35,  34,  86,  92,  37,  28,  24,  26,  95,  36,  29,  32,  93,
        19,  23,   8])

In [14]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [15]:
col_names=['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course']

In [16]:
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [17]:
col_names=['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course']
for i in col_names:
    print(f'{i}= {df[i].unique()}')

gender= ['female' 'male']
race/ethnicity= ['group B' 'group C' 'group A' 'group D' 'group E']
parental level of education= ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']
lunch= ['standard' 'free/reduced']
test preparation course= ['none' 'completed']

In [18]:
col_names=['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course']
for i in col_names:
    print(f'{i}= {df[i].nunique()}')

gender= 2
race/ethnicity= 5
parental level of education= 6
lunch= 2
test preparation course= 2

# Value_counts() returns unique value and its count
Syntax - df[col_name].value_counts()

In [19]:
df['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [20]:
df['lunch'].value_counts()

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

In [22]:
data={"age":[22,None,None ,30,60],
      'sal':[None, None, 25000,30000,40000]}
dr=pd.DataFrame(data)

In [24]:
dr

    age      sal
0  22.0      NaN
1   NaN      NaN
2   NaN  25000.0
3  30.0  30000.0
4  60.0  40000.0